import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type الحساب={id:string;business_id:string;name:string;handle:string|null;contact_email:string|null;status:"active"|"inactive"|"suspended";owner_user_id:string|null;notes:string|null;platform:{name:string}[]|null};
type Business={id:string;name:string}; type المنصة={id:string;name:string}; type UserProfile={id:string;full_name:string|null};
type Credentials={password:string;authentication_2fa:string};
const statusLabels: Record<string,string> = { active:"نشط", inactive:"غير نشط", suspended:"موقوف" };
const credentialLabels: Record<string,string> = { password:"كلمة المرور", authentication_2fa:"المصادقة / التحقق بخطوتين" };
const emptyCredentials:Credentials={password:"",authentication_2fa:""};

export function الحسابsPage({canManage,userId,role}:{canManage:boolean;userId:string;role:string}){
 const [accounts,setالحسابs]=useState<الحساب[]>([]),[businesses,setBusinesses]=useState<Business[]>([]),[platforms,setالمنصةs]=useState<المنصة[]>([]),[users,setUsers]=useState<UserProfile[]>([]);
 const [search,setSearch]=useState(""),[status,setالحالة]=useState(""),[businessId,setBusinessId]=useState(""),[platformId,setالمنصةId]=useState(""),[showForm,setShowForm]=useState(false),[editing,setتعديلing]=useState<string|null>(null);
 const [form,setForm]=useState({business_id:"",platform_id:"",name:"",handle:"",contact_email:"",owner_user_id:"",status:"active" as الحساب["status"],notes:""}),[credentials,setCredentials]=useState<Credentials>(emptyCredentials),[showCredentials,setShowCredentials]=useState(false);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[saveError,setSaveError]=useState("");

 async function load(){if(!supabase){setLoading(false);return;}setLoading(true);setError("");
 const [a,b,p,u]=await Promise.all([supabase.from("accounts").select("id,business_id,name,handle,contact_email,status,owner_user_id,notes,platform:social_platforms(name)").order("name"),supabase.from("businesses").select("id,name").eq("status","active").order("name"),supabase.from("social_platforms").select("id,name").eq("active",true).order("name"),supabase.from("profiles").select("id,full_name").eq("status","active").order("full_name")]);
 const e=[a.error,b.error,p.error,u.error].find(Boolean);if(e)setError(e.message);else{setالحسابs((a.data??[])as الحساب[]);setBusinesses((b.data??[])as Business[]);setالمنصةs((p.data??[])as المنصة[]);setUsers((u.data??[])as UserProfile[])}setLoading(false);}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>accounts.filter(a=>{const q=search.toLowerCase(),pn=a.platform?.[0]?.name??"";return(!q||[a.name,a.handle??"",a.contact_email??"",pn].some(v=>v.toLowerCase().includes(q)))&&(!status||a.status===status.trim().toLowerCase())&&(!businessId||a.business_id===businesses.find(b=>b.name.toLowerCase()===businessId.trim().toLowerCase())?.id)&&(!platformId||a.platform?.[0]?.name.toLowerCase()===platformId.trim().toLowerCase())}),[accounts,search,status,businessId,platformId,platforms]);
 function reset(){setForm({business_id:businesses[0]?.name??"",platform_id:"",name:"",handle:"",contact_email:"",owner_user_id:"",status:"active",notes:""});setCredentials(emptyCredentials);setتعديلing(null);setSaveError("")}
 function startتعديل(a:الحساب){setتعديلing(a.id);setShowForm(true);setForm({business_id:businesses.find(b=>b.id===a.business_id)?.name??a.business_id,platform_id:a.platform?.[0]?.name??"",name:a.name,handle:a.handle??"",contact_email:a.contact_email??"",owner_user_id:a.owner_user_id?users.find(u=>u.id===a.owner_user_id)?.full_name??a.owner_user_id:"",status:a.status,notes:a.notes??""});setCredentials(emptyCredentials)}
 async function save(e:FormEvent){e.preventDefault();if(!supabase||!canManage)return;setSaving(true);setSaveError("");const business=businesses.find(b=>b.name.toLowerCase()===form.business_id.trim().toLowerCase());
    const platform=platforms.find(p=>p.name.toLowerCase()===form.platform_id.trim().toLowerCase());
    const employee=users.find(u=>(u.full_name??"").trim().toLowerCase()===form.owner_user_id.trim().toLowerCase()||u.id===form.owner_user_id.trim());
    const accountالحالة=form.status.trim().toLowerCase();
    if(!business){setSaveError("يجب أن يطابق اسم الشركة شركة موجودة.");setSaving(false);return;}
    if(!platform){setSaveError("يجب أن يطابق اسم المنصة منصة موجودة.");setSaving(false);return;}
    if(form.owner_user_id.trim()&&!employee){setSaveError("يجب أن يطابق الموظف المسؤول اسم موظف موجود.");setSaving(false);return;}
    if(!["active","inactive","suspended"].includes(accountالحالة)){setSaveError("حالة الحساب يجب أن تكون: نشط، غير نشط، أو موقوف.");setSaving(false);return;}
    const payload={business_id:business.id,platform_id:platform.id,name:form.name.trim(),handle:form.handle.trim()||null,contact_email:form.contact_email.trim()||null,owner_user_id:employee?.id??null,status:accountالحالة as الحساب["status"],notes:form.notes.trim()||null};const result=editing?await supabase.from("accounts").update(payload).eq("id",editing).select("id").single():await supabase.from("accounts").insert(payload).select("id").single();if(result.error||!result.data){setSaveError(result.error?.message??"تعذر حفظ البيانات.");setSaving(false);return;}const cred=await supabase.functions.invoke("bcs-credentials",{body:{entity:"account",action:"write",entity_id:result.data.id,credentials}});if(cred.error){setSaveError("تم حفظ الحساب، لكن تعذر حفظ بيانات الدخول. لم يتم كشف أي قيمة سرية.");setSaving(false);await load();return;}setShowForm(false);reset();await load();setSaving(false);}
 async function reveal(a:الحساب){if(!(role==="admin"||a.owner_user_id===userId))return;setCredentials(emptyCredentials);setShowCredentials(true);setSaveError("");const {data,error}=await supabase!.functions.invoke("bcs-credentials",{body:{entity:"account",action:"read",entity_id:a.id}});if(error){setSaveError("تم رفض عرض بيانات الدخول أو أنها غير متاحة.");return;}setCredentials(data?.credentials??emptyCredentials)}
 async function copy(v:string){if(v)await navigator.clipboard.writeText(v)}
 return <section className="data-page"><div className="data-page-header"><div><p className="eyebrow">BCS · المرحلة الأولى</p><h1>حسابات التواصل الاجتماعي</h1><p>إدارة حسابات التواصل وبيانات كلمات المرور والمصادقة المحمية.</p></div><div className="header-actions"><span className="data-count">{filtered.length} معروض</span>{canManage&&<button className="primary-action" onClick={()=>{reset();setShowForm(v=>!v)}}>{showForm?"إغلاق":"إضافة حساب"}</button>}</div></div>
 {canManage&&showForm&&<form className="inline-form" onSubmit={save}><label>المنصة<input value={form.platform_id} onChange={e=>setForm({...form,platform_id:e.target.value})} placeholder="المنصة name" required/></label><label>اسم الحساب<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>اسم المستخدم<input value={form.handle} onChange={e=>setForm({...form,handle:e.target.value})}/></label><label>البريد الإلكتروني<input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><label>الموظف المسؤول<input value={form.owner_user_id} onChange={e=>setForm({...form,owner_user_id:e.target.value})} placeholder="Employee name"/></label><label>حالة الحساب<input value={form.status} onChange={e=>setForm({...form,status:e.target.value as الحساب["status"]})} placeholder="نشط / غير نشط / موقوف"/></label><label className="field-span-2">ملاحظات<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="credential-section field-span-2"><strong>بيانات الدخول المحمية</strong><span>تُشفّر كلمة المرور وبيانات المصادقة / التحقق بخطوتين داخل Supabase Vault.</span></div><label>كلمة المرور<input type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} autoComplete="new-password"/></label><label>المصادقة / التحقق بخطوتين<input value={credentials.authentication_2fa} onChange={e=>setCredentials({...credentials,authentication_2fa:e.target.value})}/></label>{saveError&&<p className="auth-error field-span-2">{saveError}</p>}<div className="form-actions field-span-2"><button className="primary-action" disabled={saving}>{saving?"جارٍ الحفظ…":editing?"حفظ التغييرات":"إنشاء الحساب"}</button><button type="button" className="secondary-button" onClick={()=>{setShowForm(false);reset()}}>إلغاء</button></div></form>}
 <div className="filter-bar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="البحث في حسابات التواصل…"/><input value={status} onChange={e=>setالحالة(e.target.value)} placeholder="تصفية حسب الحالة…"/><input value={businessId} onChange={e=>setBusinessId(e.target.value)} placeholder="تصفية حسب الشركة…"/><input value={platformId} onChange={e=>setالمنصةId(e.target.value)} placeholder="تصفية حسب المنصة…"/>{(search||status||businessId||platformId)&&<button type="button" className="secondary-button" onClick={()=>{setSearch("");setStatus("");setBusinessId("");setPlatformId("")}}>مسح التصفية</button>}</div>
 {loading&&<div className="loading-state">جارٍ تحميل حسابات التواصل…</div>}{!loading&&error&&<p className="auth-error">{error}</p>}{!loading&&!error&&!filtered.length&&<div className="empty-state">لا توجد حسابات تطابق عوامل التصفية الحالية.</div>}{!loading&&!error&&!!filtered.length&&<div className="data-table-wrap"><table className="data-table"><thead><tr><th>المنصة</th><th>الحساب</th><th>اسم المستخدم</th><th>البريد الإلكتروني</th><th>المسؤول</th><th>الحالة</th><th>كلمة المرور</th><th>Actions</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td>{a.platform?.[0]?.name||"—"}</td><td><strong>{a.name}</strong></td><td>{a.handle||"—"}</td><td>{a.contact_email||"—"}</td><td>{a.owner_user_id?users.find(u=>u.id===a.owner_user_id)?.full_name||"مسند":"غير مسند"}</td><td><span className="status-badge">{statusLabels[a.status]||a.status}</span></td><td>••••••••</td><td><div className="row-actions">{(role==="admin"||a.owner_user_id===userId)&&<button className="ghost-button" onClick={()=>reveal(a)}>عرض / نسخ</button>}{canManage&&<button className="ghost-button" onClick={()=>startتعديل(a)}>تعديل</button>}</div></td></tr>)}</tbody></table></div>}
 {showCredentials&&<div className="secret-modal"><div className="secret-card"><div className="data-page-header"><div><p className="eyebrow">عرض مصرح</p><h2>بيانات الدخول المحمية</h2><p>عرض البيانات السرية متاح للمسؤول الإداري والموظف المسؤول فقط.</p></div><button className="secondary-button" onClick={()=>setShowCredentials(false)}>إغلاق</button></div>{saveError&&<p className="auth-error">{saveError}</p>}{Object.entries(credentials).map(([k,v])=><div className="secret-row" key={k}><span>{credentialLabels[k]||k}</span><input readOnly type={k==="password"?"password":"text"} value={v}/><button className="ghost-button" onClick={()=>copy(v)}>نسخ</button></div>)}</div></div>}
 </section>
}
