import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Account={id:string;business_id:string;name:string;handle:string|null;contact_email:string|null;status:"active"|"inactive"|"suspended";owner_user_id:string|null;notes:string|null;platform:{name:string}[]|null};
type Business={id:string;name:string}; type Platform={id:string;name:string}; type UserProfile={id:string;full_name:string|null};
type Credentials={password:string;authentication_2fa:string};
const emptyCredentials:Credentials={password:"",authentication_2fa:""};

export function AccountsPage({canManage,userId,role}:{canManage:boolean;userId:string;role:string}){
 const [accounts,setAccounts]=useState<Account[]>([]),[businesses,setBusinesses]=useState<Business[]>([]),[platforms,setPlatforms]=useState<Platform[]>([]),[users,setUsers]=useState<UserProfile[]>([]);
 const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[businessId,setBusinessId]=useState(""),[platformId,setPlatformId]=useState(""),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<string|null>(null);
 const [form,setForm]=useState({business_id:"",platform_id:"",name:"",handle:"",contact_email:"",owner_user_id:"",status:"active" as Account["status"],notes:""}),[credentials,setCredentials]=useState<Credentials>(emptyCredentials),[showCredentials,setShowCredentials]=useState(false);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[saveError,setSaveError]=useState("");

 async function load(){if(!supabase){setLoading(false);return;}setLoading(true);setError("");
 const [a,b,p,u]=await Promise.all([supabase.from("accounts").select("id,business_id,name,handle,contact_email,status,owner_user_id,notes,platform:social_platforms(name)").order("name"),supabase.from("businesses").select("id,name").eq("status","active").order("name"),supabase.from("social_platforms").select("id,name").eq("active",true).order("name"),supabase.from("profiles").select("id,full_name").eq("status","active").order("full_name")]);
 const e=[a.error,b.error,p.error,u.error].find(Boolean);if(e)setError(e.message);else{setAccounts((a.data??[])as Account[]);setBusinesses((b.data??[])as Business[]);setPlatforms((p.data??[])as Platform[]);setUsers((u.data??[])as UserProfile[])}setLoading(false);}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>accounts.filter(a=>{const q=search.toLowerCase(),pn=a.platform?.[0]?.name??"";return(!q||[a.name,a.handle??"",a.contact_email??"",pn].some(v=>v.toLowerCase().includes(q)))&&(!status||a.status===status.trim().toLowerCase())&&(!businessId||a.business_id===businesses.find(b=>b.name.toLowerCase()===businessId.trim().toLowerCase())?.id)&&(!platformId||a.platform?.[0]?.name.toLowerCase()===platformId.trim().toLowerCase())}),[accounts,search,status,businessId,platformId,platforms]);
 function reset(){setForm({business_id:businesses[0]?.id??"",platform_id:"",name:"",handle:"",contact_email:"",owner_user_id:"",status:"active",notes:""});setCredentials(emptyCredentials);setEditing(null);setSaveError("")}
 function startEdit(a:Account){setEditing(a.id);setShowForm(true);setForm({business_id:a.business_id,platform_id:platforms.find(p=>p.name===a.platform?.[0]?.name)?.id??"",name:a.name,handle:a.handle??"",contact_email:a.contact_email??"",owner_user_id:a.owner_user_id??"",status:a.status,notes:a.notes??""});setCredentials(emptyCredentials)}
 async function save(e:FormEvent){e.preventDefault();if(!supabase||!canManage)return;setSaving(true);setSaveError("");const business=businesses.find(b=>b.name.toLowerCase()===form.business_id.trim().toLowerCase());
    const platform=platforms.find(p=>p.name.toLowerCase()===form.platform_id.trim().toLowerCase());
    const employee=users.find(u=>(u.full_name??"").trim().toLowerCase()===form.owner_user_id.trim().toLowerCase()||u.id===form.owner_user_id.trim());
    const accountStatus=form.status.trim().toLowerCase();
    if(!business){setSaveError("Business must match an existing business name.");setSaving(false);return;}
    if(!platform){setSaveError("Platform must match an existing platform name.");setSaving(false);return;}
    if(form.owner_user_id.trim()&&!employee){setSaveError("Responsible employee must match an existing employee name.");setSaving(false);return;}
    if(!["active","inactive","suspended"].includes(accountStatus)){setSaveError("Account status must be Active, Inactive, or Suspended.");setSaving(false);return;}
    const payload={business_id:business.id,platform_id:platform.id,name:form.name.trim(),handle:form.handle.trim()||null,contact_email:form.contact_email.trim()||null,owner_user_id:employee?.id??null,status:accountStatus as Account["status"],notes:form.notes.trim()||null};const result=editing?await supabase.from("accounts").update(payload).eq("id",editing).select("id").single():await supabase.from("accounts").insert(payload).select("id").single();if(result.error||!result.data){setSaveError(result.error?.message??"Unable to save.");setSaving(false);return;}const cred=await supabase.functions.invoke("bcs-credentials",{body:{entity:"account",action:"write",entity_id:result.data.id,credentials}});if(cred.error){setSaveError("Account saved, but credential storage failed. No credential value was exposed.");setSaving(false);await load();return;}setShowForm(false);reset();await load();setSaving(false);}
 async function reveal(a:Account){if(!(role==="admin"||a.owner_user_id===userId))return;setCredentials(emptyCredentials);setShowCredentials(true);setSaveError("");const {data,error}=await supabase!.functions.invoke("bcs-credentials",{body:{entity:"account",action:"read",entity_id:a.id}});if(error){setSaveError("Credential reveal was denied or unavailable.");return;}setCredentials(data?.credentials??emptyCredentials)}
 async function copy(v:string){if(v)await navigator.clipboard.writeText(v)}
 return <section className="data-page"><div className="data-page-header"><div><p className="eyebrow">BCS · PHASE 1</p><h1>Social Media Accounts</h1><p>Social account ownership and protected password / authentication records.</p></div><div className="header-actions"><span className="data-count">{filtered.length} shown</span>{canManage&&<button className="primary-action" onClick={()=>{reset();setShowForm(v=>!v)}}>{showForm?"Close":"Add account"}</button>}</div></div>
 {canManage&&showForm&&<form className="inline-form" onSubmit={save}><label>Platform<input value={form.platform_id} onChange={e=>setForm({...form,platform_id:e.target.value})} placeholder="Platform name" required/></label><label>Account name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Username<input value={form.handle} onChange={e=>setForm({...form,handle:e.target.value})}/></label><label>Email<input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><label>Responsible employee<input value={form.owner_user_id} onChange={e=>setForm({...form,owner_user_id:e.target.value})} placeholder="Employee name"/></label><label>Account status<input value={form.status} onChange={e=>setForm({...form,status:e.target.value as Account["status"]})} placeholder="Active / Inactive / Suspended"/></label><label className="field-span-2">Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="credential-section field-span-2"><strong>Protected credentials</strong><span>Password and authentication / 2FA are encrypted in Supabase Vault.</span></div><label>Password<input type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} autoComplete="new-password"/></label><label>Authentication / 2FA<input value={credentials.authentication_2fa} onChange={e=>setCredentials({...credentials,authentication_2fa:e.target.value})}/></label>{saveError&&<p className="auth-error field-span-2">{saveError}</p>}<div className="form-actions field-span-2"><button className="primary-action" disabled={saving}>{saving?"Saving…":editing?"Save changes":"Create account"}</button><button type="button" className="secondary-button" onClick={()=>{setShowForm(false);reset()}}>Cancel</button></div></form>}
 <div className="filter-bar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search social accounts…"/><input value={status} onChange={e=>setStatus(e.target.value)} placeholder="Filter status…"/><input value={businessId} onChange={e=>setBusinessId(e.target.value)} placeholder="Filter business…"/><input value={platformId} onChange={e=>setPlatformId(e.target.value)} placeholder="Filter platform…"/></div>
 {loading&&<div className="loading-state">Loading social accounts…</div>}{!loading&&error&&<p className="auth-error">{error}</p>}{!loading&&!error&&!filtered.length&&<div className="empty-state">No social media accounts match the current filters.</div>}{!loading&&!error&&!!filtered.length&&<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Platform</th><th>Account</th><th>Username</th><th>Email</th><th>Responsible</th><th>Status</th><th>Password</th><th>Actions</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td>{a.platform?.[0]?.name||"—"}</td><td><strong>{a.name}</strong></td><td>{a.handle||"—"}</td><td>{a.contact_email||"—"}</td><td>{a.owner_user_id?users.find(u=>u.id===a.owner_user_id)?.full_name||"Assigned":"Not assigned"}</td><td><span className="status-badge">{a.status}</span></td><td>••••••••</td><td><div className="row-actions">{(role==="admin"||a.owner_user_id===userId)&&<button className="ghost-button" onClick={()=>reveal(a)}>Reveal / copy</button>}{canManage&&<button className="ghost-button" onClick={()=>startEdit(a)}>Edit</button>}</div></td></tr>)}</tbody></table></div>}
 {showCredentials&&<div className="secret-modal"><div className="secret-card"><div className="data-page-header"><div><p className="eyebrow">AUTHORIZED VIEW</p><h2>Protected credentials</h2><p>Reveal is restricted to administrators and the responsible employee.</p></div><button className="secondary-button" onClick={()=>setShowCredentials(false)}>Close</button></div>{saveError&&<p className="auth-error">{saveError}</p>}{Object.entries(credentials).map(([k,v])=><div className="secret-row" key={k}><span>{k.replaceAll("_"," ")}</span><input readOnly type={k==="password"?"password":"text"} value={v}/><button className="ghost-button" onClick={()=>copy(v)}>Copy</button></div>)}</div></div>}
 </section>
}
